### ISSUE TITLE
Triple Beam.Pro Chats in Program

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#10]
I was streaming last night and for some weird reason, the Beam.pro chat kept duplicating itself by three twice last night. I am using a bot called BenBot for Beam. It didn't show any issues like that and only appeared on Ubiquitous 2.

Is there a way to look up the logs for your program in case it happens again?

**Comment by xedoc** [comment]
There no logs to track it but I'll try to catch it somehow. It could be some problem with reconnect when network is lost.

**Comment by Draygera** [comment]
Probably. I've been having network issues lately. So that would make a lot of sense

**Comment by xedoc** [comment]
Shouldn't happen again

**Comment by Draygera** [comment]
I'll test it out again tonight, but last night, Gaming.tv started doing it at random too.

**Comment by xedoc** [comment]
I'm publishing update right now. Ping timeout for Beam.pro has been increased. There also fix for performance issue.

**Comment by Draygera** [comment]
What's the average bandwidth usage for your program? I'm asking because I was thinking that a huge part of the issues I've been having might be due to not allocating enough bandwidth to Ubiquitous and setting my bitrate too high for the stream. I have only a 1 MB upload right now (need to move to get faster internet) and setting my bitrate to between 500 and 625 usually works the best when I stream at 360p.

**Comment by xedoc** [comment]
It depend on message rate mostly. You can use standard Resource Monitor and check it on Network tab. But it shouldn't affect upload bandwith too much.

**Comment by xedoc** [comment]
BTW I've catch that bug with continous beam.pro reconnect. Checking it further...

**Comment by Draygera** [comment]
Could I possibly help with the code at all? I mostly know Java but C# and Java seem very similar in implementation.

**Comment by xedoc** [comment]
Well if you have free time for that :D You can try to add some new chat support.

**Comment by Draygera** [comment]
When I'm not streaming or working, I have a lot of free time.

**Comment by xedoc** [comment]
I believe it is fixed now ;)
