### ISSUE TITLE
Beam.Pro Emotes Not Showing

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#11]
I don't know if this was a design choice or a bug, but none of the Beam.pro emotes show up at all in the chat program for me.

**Comment by xedoc** [comment]
They've changed protocol a bit. Before that emoticon url was in message. Now there coordinates only. It seems I need to find the image with all icons and crop it to get specified emoticon.

**Comment by Draygera** [comment]
Awww. So basically a Texture Atlas now?

**Comment by xedoc** [comment]
Yes but there nothing impossible :)

**Comment by Draygera** [comment]
Also, did you see this: https://github.com/WatchBeam/emoticons. That's a github for all of Beam's current emotes.

**Comment by xedoc** [comment]
Beam.pro emoticons fixed

**Comment by Draygera** [comment]
Working as advertised. XD
