### ISSUE TITLE
Chats Randomly Disconnecting

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#12]
Several of my chats don't always show messages from my viewers. Youtube and Beam.pro especially

**Comment by Draygera** [comment]
Actually, latest update completely disconnected all chats at random. I love your program but I have no clue why it's doing this...

**Comment by xedoc** [comment]
Well... I changed connection handling in latest update. Beam.pro and Youtube didn't go red if connection was lost. Now they show network status properly and trying to reconnect if network lost.

**Comment by Draygera** [comment]
Last night, I had to restart 3 times before my chats started working again. The one that kept disconnecting consistently was Connectcast afterwards.

**Comment by xedoc** [comment]
Could you please check if web chat reconnect also when that happens ? Most of sites show that right in the chat window but you can use Developer console in Chrome and check if websocket connection is creating multiple times. That will mean that you have problem with connection.

**Comment by Draygera** [comment]
I can try that out. I actually use Opera since Chrome caused a lot of issues with my streaming. They both should have the same Developer Console.

**Comment by Draygera** [comment]
Haven't checked out your test yet but all chats keep disconnecting still. Twitch and Beam are the most prone to right now.

**Comment by xedoc** [comment]
I tested beam.pro and it disconnects on the website too. So it could be something with their service...

**Comment by Draygera** [comment]
They are doing a massive update right now and it's having problems with quite a few people as they work out the kinks. Twitch I'm not so sure about.

**Comment by xedoc** [comment]
Well I don't have that problem with Twitch. It rock stable on my side :/ Will test further

**Comment by Draygera** [comment]
Idk if it was a fluke, but last night, this issue didn't crop up at all. Other issues cropped up (as posted in separate Bug Reports). Gonna test out again tonight.

**Comment by Tsunami2069** [comment]
If by "disconnecting" you mean that the chat stops coming to ubiquitous, then mine has been having the same problem.
I find myself having to restart ubiquitous several times during my streams.
I've checked the web and it too stops get chat lines. haven't checked the websocket connetion, though... Will try it on my next stream.
Im using with twitch and hitbox chats, for now, planning on adding Youtube to it later.

**Comment by Draygera** [comment]
Yup. Twitch and Beam both have been disconnecting quite a bit lately for me, @Tsunami2069. I know that Beam's been doing a lot of behind the scenes stuff, but it's a pretty solid service if you'd like to check it out. Also, Youtube Gaming works great on Ubiquitous with the exception of some delay

**Comment by Tsunami2069** [comment]
Yeah, i just added my Youtube chat to ubiquitous and it works... But it still kinda sucks that the Twitch and / or hitbox chat stops working and i have to restart ubiquitous2 several times.
I ran ubiquitous2 through developer chrome and haven't seen anything unusual.

**Comment by xedoc** [comment]
Update is on the way. Let see if it help

**Comment by Draygera** [comment]
@Tsunami2069 Have you been having massive CPU spikes and freezing with the program? I've been having that issue on and off again, too

**Comment by xedoc** [comment]
Please check current update. CPU usage and freezes should be fixed now.

**Comment by Tsunami2069** [comment]
@Draygera I haven't been monitoring CPU usage but i didnt notice anything out of the ordinary.

@xedoc Thanks a lot m8... I will report back on the my next stream, prolly tomorrow or on wednesday.

**Comment by Draygera** [comment]
@Tsunami2069 I was doing a stream last night and Ubiquitous was using up almost 50% of my CPU. I have a 4 GHz AMD Quad Core. Weirdest thing ever

**Comment by Tsunami2069** [comment]
Alright, @Draygera and @xedoc i think u can close this issue.
I streamed for 3 hours today (a small stream) and ubiquitous didn't disconnect once.~
I also checked my CPU usage from time to time and it was low.

Good stuff, xedoc. Thanks a lot bro.

**Comment by xedoc** [comment]
Thank you for test!
