### ISSUE TITLE
Images No Longer Show Up In Chat

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#13]
I don't know what happened but recently images have started only showing up as links. It started two or three updates ago.

**Comment by xedoc** [comment]
How do you post images ? Via img tag or just link ?

**Comment by Draygera** [comment]
Just link. Do I need to use IMG tag?

**Comment by xedoc** [comment]
Yep I didn't implement link to image conversion yet.

**Comment by Draygera** [comment]
Interesting. When I first started using your program, Hitbox images almost always showed.

**Comment by xedoc** [comment]
Now when permission list is implemented - I can parse links to images.

**Comment by xedoc** [comment]
Should work with img tags and normal links now
