### ISSUE TITLE
Typing Beam.pro Emotes in Strange Bug

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#14]
Typing Emotes in program with Beam.pro chat selected causes streamer to send back the last two Beam.pro messages instead of showing emote. Don't know why this is happening, but it did.

**Comment by Draygera** [comment]
So, tonight, this bug actually didn't appear. Will keep testing. Might have just been a fluke for the day yesterday.

**Comment by xedoc** [comment]
Shouldn't happen anymore.
