### ISSUE TITLE
Youtube StreamNow Beta Implementation

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#16]
I don't know if you've been keeping up with it, but Youtube is now starting to push a different streaming implementation that will quite possibly replace its Live Events as it gets ready for YoutubeGaming to be a thing. When can this be expected to be added to Ubiquitous and what would it take to get it going? I don't think the protocols used would be that much different.

**Comment by xedoc** [comment]
Yes I know but I don't have an access there. I'll check it right when it become public.

**Comment by Draygera** [comment]
Update: Apparently StreamNow Beta and Live Events both use the same protocol. I was getting my normal Youtube messages the other night using only StreamNow, so I don't think that there's any major work needed to be done with it right now, other than it sometimes disconnecting like the rest of the services have still been doing from time to time.
