### ISSUE TITLE
Streamup Bug

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#18]
Parsing of chat variables Failed is the message I keep getting.

**Comment by Draygera** [comment]
Nvm. I put the wrong password in. Derp

**Comment by Draygera** [comment]
Just figured it out. You have to use your email address to login to Streamup or it won't work. That's kinda dumb

**Comment by xedoc** [comment]
Yep, thats how it work on the site. It accept email only.

**Comment by Draygera** [comment]
I figured as much. Might be a good idea to change UserName to Email address in program to help people with possible confusion.

**Comment by Draygera** [comment]
Thanks for updating it to say Email. Definitely a major improvement.
