### ISSUE TITLE
[bug?] using options to make the chat window click-through causes window to disappear

### ISSUE THREAD

**Issue by KinamKrindar** [xedoc/Ubiquitous2#2]
When trying to use the ability to click-through the chat window, the window disappears for me. Un-checking that option does not bring window back initially, have to click on it to get some of it back. Must move window to make it fully visible again.

**Comment by KinamKrindar** [comment]
Apparently the "enable window background transparency" is what was needed. Apparently trying to have click-through without that, makes the whole window disappear.

I'll leave this one open for you to investigate that possibility? the other issue and this one apparently were connected, so I'm good now. However perhaps this being a "bug" with those certain circumstances, see if it's something you can replicate with this new information?

**Comment by xedoc** [comment]
Thats how Windows work. There no way to make window click-through without making it transparent.

**Comment by KinamKrindar** [comment]
k, not familiar with coding windows stuff at all. Perhaps make it so that you can't choose the click-through without the transparency thing? or have a warning saying that you should enable the transparency
