### ISSUE TITLE
[ENHANCEMENT] Extra Chat Sites Support

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#4]
I'm a multi-streamer and would love to have support added to your program for the sites listed below:

Stream.me
games.dailymotion.com
Streamup.com

I know that Stream.me is really new and Dailymotion and Streamup's streaming services are both subpar at best, but I still would like to have the ability to display their chats on my stream so that the rest of my viewers know what's going on with the other sites I use. Thank you.

**Comment by xedoc** [comment]
Hi, dailymotion is on list. I'll check others. Shouldn't be a problem to add them

**Comment by Draygera** [comment]
Thanks.
