### ISSUE TITLE
Crashes At Random With Latest Update

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#9]
Here's the event logs for your perusal:

http://pastebin.com/yMufR0hb

**Comment by xedoc** [comment]
Trying to catch it but latest update isn't cause. I guess it happens on sudden disconnect...

**Comment by xedoc** [comment]
Hitbox.tv should be fixed now. There was a bug with user list accessed from multiple threads. Connectcast.tv needs to be tested. I've added few checks for null reference, though I'm not sure on which line it have been crashed.

**Comment by Draygera** [comment]
Man, you are awesome. It didn't start crashing on me until I updated it this morning, so I have no clue.

**Comment by Draygera** [comment]
So far, since the last update, I've not had any crashes at all. If it doesn't crash tonight, I will go ahead and close this issue out.
